{% set name = "stripnet" %}
{% set version = "0.0.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/stripnet-{{ version }}.tar.gz
  sha256: 40abb57cc734361d8e3c9178b844b7549f5ea829ea02b2353c7bc82025994bf2

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }},<3.9
    - bertopic >=0.9.4
    - ipywidgets >=7.6.5
    - networkx >=2.6.3
    - numpy >=1.22.0
    - pandas >=1.3.5
    - plotly >=5.5.0
    - pyvis >=0.1.9
    - scikit-learn >=1.0.2
    - sentence-transformers >=2.1.0

test:
  imports:
    - stripnet
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/stephenleo/stripnet
  summary: 'STriP Net: Semantic Similarity of Scientific Papers (S3P) Network'
  license: Apache-2.0
  license_file: LICENSE
  description: |
    Leverage the power of NLP Topic Modeling, Semantic Similarity and Network 
    analysis to study the themes and semantical relations within a corpus of 
    research papers.

    PyPI: [https://pypi.org/project/stripnet/](https://pypi.org/project/stripnet/)

  doc_url: https://github.com/stephenleo/stripnet
  dev_url: https://github.com/stephenleo/stripnet

extra:
  recipe-maintainers:
    - sugatoray
    # Maintainer(s) from stripnet repo
    - stephenleo
